### ISSUE TITLE
[Miranum-Deployment-Showcase] - Create a showcase for file deployments

### ISSUE THREAD

**Issue by lmoesle** [Miragon/miranum-consulting#36]
- [ ] Description created
- [ ] Reviewed by peer: <tag-person-here>
- [ ] Prioritised

# Description

We need a showcase to show customers how to use miranum-deployment:

- **Deployment of bpmn, dmn, json schema forms, json configs:** The showcase should demonstrate how to deploy these different types of files using miranum-deployment. This should include using Miranum-cli to deploy files, as well as creating a small example app and using miranum-core to deploy files to the miranum-server
- **How to implement miranum-deployment:** The showcase should also demonstrate how to implement miranum-deployment. This should include creating an example using the miranum-deployment server and implementing the miranum-deployment receiver in at least two custom spring boot apps.
- **Creating documentation:** Write a README.md together with the code and add the showcase to our website (https://miranum.com/docs/guides/showcases/showcases-overview)
- Finally create a blogpost to promote the showcase

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] First create a simple example project with bpmn, dmn and json schema forms and use the miranum-cli to deploy them to a miranum-deployment server
- [ ] Create a simple frontend application (Upload a file and deploy it directly) that uses the miranum-core to deploy files to a miranum-deployment-server
- [ ] Create an engine service using camunda 7 and implement bpmn and dmn deployment using the miranum-deployment-receiver
- [ ] Create a spring boot application that implements the miranum-deployment-receiver for json schema file (form) deployments
- [ ] Create a README.md together with the code
- [ ] Create documentation for the showcase at the miranum website (https://miranum.com/docs/guides/showcases/showcases-overview)
- [ ] Finally, write a blogpost about the showcase
```

**Comment by lmoesle** [comment]
Documentation for miranum-cli and miranum-core:
- miranum-cli: https://www.npmjs.com/package/@miragon/miranum-cli
- miranum-core: https://www.npmjs.com/package/@miragon/miranum-core
The documentation is not 100% up-to-date
